<?xml version="1.0" encoding="utf-8"?><Database Name="hotel" Class="HotelDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-1OIQVR6\;Initial Catalog=hotel;Integrated Security=True" SettingsObjectName="hotel_project1.Properties.Settings" SettingsPropertyName="hotelConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="employee_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="salary" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="job" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="national_code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Guest" Member="Guests">
    <Type Name="Guest">
      <Column Name="guest_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="user_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="isVip" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="room_num" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rooms" Member="Rooms">
    <Type Name="Room">
      <Column Name="room_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="room_num" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="reserve_date" Type="System.DateTime" DbType="DateTime" CanBeNull="false" />
      <Column Name="days_reserve" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="isEmpty" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>